[package]
name = "ungrammar-gen"
version = "0.1.0"
edition = "2021"


[dependencies]
ungrammar-extra = { path="../ungrammar-extra" }

eyre = "0.6.12"
heck = "0.4.1"

proc-macro2 = "1.0.78"
quote = "1.0.35"

ungrammar = "1.16.1"
indoc = "2.0.4"
syn = { version = "2.0.52", features = ["full"] }

